"""Restore-token authentication (spec L3, v0.3).

Standard library only. The token is generated by ``zee
init-restore-token`` and stored at ``~/.zee/restore_token`` (0600);
``zee restore`` requires it via ``--token`` or the
``ZEE_RESTORE_TOKEN`` environment variable.

Threat model — what this stops, and what it does not:
    * Stops: a non-root attacker who has a shell on the host but has
      not enumerated ``~/.zee/`` yet, and accidental restores from a
      second shell session.
    * Does NOT stop: a root-equivalent attacker (they can read the
      token file directly). For multi-user production deployments,
      README recommends wrapping ``zee restore`` in ``sudo`` or
      running Zee under a dedicated user; ``restore_token`` is a
      complement, not a replacement, for OS-level access control.

Implementation choices:
    * 256-bit token (``secrets.token_urlsafe(32)``).
    * Comparison uses ``hmac.compare_digest`` for constant-time
      checks.
    * The token file MUST be 0600 with parent 0700; ``load_token``
      refuses files whose permissions widen those bits.
"""

from __future__ import annotations

import hmac
import logging
import os
import secrets
import stat
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def default_token_path() -> Path:
    return Path.home() / ".zee" / "restore_token"


def init_token(*, path: Optional[Path] = None) -> str:
    """Generate a new restore token and write it to disk.

    Returns the token. Overwrites any existing token file. The caller
    is responsible for displaying the token to the operator (the CLI
    does so once, to stderr).
    """
    p = path or default_token_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(p.parent, 0o700)
    except (OSError, NotImplementedError):
        pass
    token = secrets.token_urlsafe(32)
    p.write_text(token + "\n", encoding="utf-8")
    try:
        os.chmod(p, 0o600)
    except (OSError, NotImplementedError):
        pass
    return token


def load_token(*, path: Optional[Path] = None) -> Optional[str]:
    """Load the stored token, or None if not initialised / unsafe perms.

    Refuses files whose group/world bits are set (read or write) —
    a token readable by other users defeats its purpose.
    """
    p = path or default_token_path()
    if not p.exists():
        return None
    try:
        mode = stat.S_IMODE(os.stat(p).st_mode)
    except OSError as e:
        logger.warning("restore_token stat failed: %s", e)
        return None
    if mode & (stat.S_IRGRP | stat.S_IWGRP | stat.S_IROTH | stat.S_IWOTH):
        logger.error(
            "restore_token at %s has loose permissions (mode %o); refusing "
            "to load. chmod 600 %s, then retry.",
            p, mode, p,
        )
        return None
    try:
        return p.read_text(encoding="utf-8").strip()
    except OSError as e:
        logger.warning("restore_token read failed: %s", e)
        return None


def verify_token(provided: str, *, path: Optional[Path] = None) -> bool:
    """Return True iff ``provided`` matches the stored token.

    Uses ``hmac.compare_digest`` for constant-time comparison. Returns
    False when the token has not been initialised or when the file is
    unreadable / has loose perms.
    """
    stored = load_token(path=path)
    if stored is None:
        return False
    return hmac.compare_digest(provided, stored)
